# Generated by Django 2.0 on 2019-09-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190917_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='content',
            field=models.TextField(),
        ),
    ]
